# Generated by Django 4.2.16 on 2024-11-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_address_remove_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
