# Generated by Django 4.2.16 on 2024-10-15 03:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tax',
        ),
    ]
