# Generated by Django 4.2.16 on 2024-10-15 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_tax_remove_cart_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.tax'),
        ),
    ]
