# Generated by Django 4.2.16 on 2024-10-18 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='order_number')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('zip_code', models.CharField(blank=True, max_length=50, verbose_name='zip_code')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address_line_1', models.CharField(max_length=50, verbose_name='address_line_1')),
                ('address_line_2', models.CharField(blank=True, max_length=50, verbose_name='address_line_2')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('order_note', models.CharField(blank=True, max_length=1000, verbose_name='order_note')),
                ('order_total', models.FloatField(verbose_name='order_total')),
                ('tax', models.FloatField(verbose_name='tax')),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=15, verbose_name='status')),
                ('ip', models.CharField(blank=True, max_length=50, verbose_name='ip')),
                ('is_orderd', models.BooleanField(default=False, verbose_name='is_orderd')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, verbose_name='payment_id')),
                ('payment_method', models.CharField(max_length=100, verbose_name='payment_method')),
                ('payment_paid', models.CharField(max_length=100, verbose_name='payment_paid')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user payment')),
            ],
            options={
                'verbose_name': 'Payments',
                'verbose_name_plural': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('product_price', models.FloatField(verbose_name='product_price')),
                ('ordered', models.BooleanField(default=False, verbose_name='ordered')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.payment', verbose_name='payment order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='order product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user order')),
                ('variations', models.ManyToManyField(blank=True, to='store.variation')),
            ],
            options={
                'verbose_name': 'Order Products',
                'verbose_name_plural': 'Order Products',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.payment', verbose_name='payment order'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user order'),
        ),
    ]
