# Generated by Django 4.2.16 on 2024-10-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('On Delivery', 'On Delivery'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=15, verbose_name='status'),
        ),
    ]
