# Generated by Django 4.2.16 on 2025-05-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_reservation_refundpayment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancellation_date',
        ),
    ]
